global using Dalamud.Game.ClientState.Conditions;
global using Dalamud.Interface;
global using Dalamud.Interface.Colors;
global using Dalamud.Interface.Windowing;
global using Dalamud.Plugin;
global using ECommons;
global using ECommons.DalamudServices;
global using ECommons.ImGuiMethods;
global using ECommons.Logging;
global using ECommons.Schedulers;
global using Dalamud.Bindings.ImGui;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading.Tasks;
global using static ECommons.GenericHelpers;
global using static TextAdvance.TextAdvance;
global using CSFramework = FFXIVClientStructs.FFXIV.Client.System.Framework.Framework;
global using S = TextAdvance.Services.ServiceManager;
global using Player = ECommons.GameHelpers.LegacyPlayer.Player;